sudo: false
cache: apt
language: cpp
compiler:
  - g++
  - clang++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
      - llvm-toolchain-precise
    packages:
      - clang-3.8
      - g++-6
      - gcc-6
install:
  - if [ "$CXX" = 'g++' ]; then export CC='g++-6 -std=gnu11' CXX='g++-6 -std=gnu++14'; fi
  - if [ "$CXX" = 'clang++' ]; then export CC='clang-3.8 -std=gnu11' CXX='clang++-3.8 -std=gnu++14'; fi
script: make CXX="$CXX" && make test
