language: cpp
compiler:
  - g++
  - clang++
install:
  - if [ "$CXX" = 'g++' ]; then export CXX='g++-5 -std=gnu++14'; fi
  - if [ "$CXX" = 'clang++' ]; then export CXX='clang++-3.7 -std=gnu++14'; fi
script: make CXX="$CXX" && make test
sudo: false
