language: cpp
compiler:
  - g++
  - clang++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise
    packages:
      - clang-3.7
      - g++-5
      - gcc-5
install:
  - if [ "$CXX" = 'g++' ]; then export CXX='g++-5 -std=gnu++14'; fi
  - if [ "$CXX" = 'clang++' ]; then export CXX='clang++-3.7 -std=gnu++14'; fi
script: make CXX="$CXX" && make test
sudo: false
