version: 1.0.{build}
install:
- cmd: >-
    git submodule update --init

    "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
build_script:
- cmd: nmake /nologo /f msvc.mk
test_script:
- cmd: nmake /nologo /f msvc.mk test
artifacts:
- path: brainfuck.exe
  name: Brainfuck interpreter/compiler
